### ISSUE TITLE
Alignment issues - not matching screenshot

### ISSUE THREAD

**Issue by C-G-G** [C-G-G/type-those-grids#1]
It's almost done but still not matching the screenshot:

- Not sure how to move `<figcaption>` (h2 and p) on top of img... tried z-index but no luck;

- Header (img) doesn't seem to be stretching across the page... tried align-self property but no luck;

@thomasjbradley

**Comment by thomasjbradley** [comment]
For the banner image: `<figure>` tags have margins by default that you’ll want to get rid of.

You’ve got the grid set up nicely, but because of the structure of the HTML it’s impossible to move things to the right grid areas. Because grid only affects its direct children.

We need to make the banner pieces be direct children of `<main>`.
Remove `<header>`, `<figure>` and have the `<figcaption>` be directly inside `<main>`

**Comment by C-G-G** [comment]
Thanks so much for your suggestions, the page is now almost identical to the screenshot! 

Markbot is not very happy with changes made to HTML though and still expecting the elements `<header>` and `<figure>` but hey, we humans are happy and c'est la vie :)

**Comment by thomasjbradley** [comment]
Yeah, Markbot can be very persnickety.
